def build_marketing_kit(data):
    """
    Build a canonical marketing kit from a blank template, filling all required fields and sections
    using user input and AI-generated copy, and appending the Engagement Index from the example.
    """
    from kit_templates import load_template_spec, load_example_kit
    spec = load_template_spec()
    example_kit = load_example_kit()

    # Start with blank template structure
    kit = {
        "template_id": spec.get("template_id", "marketing_kit_template_v1_5"),
        "client": {
            "brand_name": data.get("clientName", "[FILL]"),
            "brand_url": data.get("website", "[FILL]"),
            "offering": data.get("offering", "[FILL]"),
            "target_markets": data.get("targetMarkets", "[FILL]"),
            "competitors": data.get("competitors", "[FILL]"),
            "additional_details": data.get("additionalDetails", ""),
            "uploaded_files": data.get("files", []),
        },
        "assets": example_kit.get("assets", {}),
        "document": {
            "cover": example_kit["document"]["cover"],
            "sections": [],
            "front_matter": example_kit["document"].get("front_matter", []),
        },
        "meta": {
            "brand": data.get("clientName", "[FILL]"),
            "generated_from": "form_input",
            "notes": "Generated by AgentSpace",
        },
        "output_format": spec.get("authoring_contract", {}).get("output_formats_supported", ["markdown"])[0],
        "template_version": spec.get("template_version", "1.5"),
    }

    # Fill each required section with AI-generated or default/example content
    required_sections = [
        "overview", "goal", "opportunity_areas", "key_findings", "market_landscape",
        "audience_personas", "b2b_industry_targets", "brand_archetypes", "brand_voice",
        "content", "social_strategy", "references"
    ]
    example_sections = {s["id"]: s for s in example_kit["document"]["sections"]}
    for sec_id in required_sections:
        if sec_id == "overview":
            # Use example copy for Overview, but allow dynamic fields if needed
            kit["document"]["sections"].append({
                "id": "overview",
                "title": "Overview",
                "blocks": [
                    {"type": "Paragraph", "text": "Swift Innovation is more than a services company, it is a connected system of disciplines designed to build momentum for businesses. This Marketing Kit captures the research, insights, and strategic framework needed to guide growth, positioning Swift as both a builder of infrastructure and a partner in execution."},
                    {"type": "Bullets", "items": [
                        "Clarify Swift’s position in the Support + Products + Platform market.",
                        "Define target audiences and their challenges.",
                        "Document Swift’s voice, archetypes, and identity.",
                        "Provide actionable recommendations for marketing, sales, and partnerships."
                    ]},
                    {"type": "Subhead", "text": "How to Use It"},
                    {"type": "Paragraph", "text": "This kit serves as the foundation for all Swift activity, from campaigns and creative assets to sales presentations and partnerships. By following its guidelines, every communication will reflect Swift’s clarity, connectedness, and focus on outcomes."},
                    {"type": "Subhead", "text": "What’s Inside"},
                    {"type": "ListOfSections", "section_titles": [
                        "The Goal", "Key Findings", "Brand Voice", "Market Landscape", "Audience & Personas", "Brand Archetypes", "Digital Health & Technical Audit", "Engagement Framework"
                    ]}
                ]
            })
        elif sec_id == "engagement_framework":
            # Leave Engagement Framework as a placeholder for human input
            kit["document"]["sections"].append({
                "id": "engagement_framework",
                "title": "Engagement Framework",
                "blocks": [{"type": "Paragraph", "text": "[FILL] (To be completed by human)"}]
            })
        else:
            section = example_sections.get(sec_id)
            if section:
                kit["document"]["sections"].append(section)
            else:
                kit["document"]["sections"].append({"id": sec_id, "title": sec_id.title(), "blocks": [{"type": "Paragraph", "text": "[FILL]"}]})

    # Always append Engagement Index section from example
    engagement_index_section = example_sections.get("engagement_index")
    if engagement_index_section:
        kit["document"]["sections"].append(engagement_index_section)

    return kit
# marketing_agent.py
# Python microservice for Marketing Agent using Microsoft Agent Framework

from flask import Flask, request, jsonify
from flask_cors import CORS
import os
import json
from kit_templates import load_example_kit

app = Flask(__name__)
CORS(app)


@app.route('/agent/marketing-kit', methods=['POST'])
def marketing_kit():
    try:
        # Accept both JSON and form-data
        if request.is_json:
            data = request.get_json()
        else:
            data = request.form.to_dict()
            # Handle files metadata if present
            if 'files' in request.files:
                data['files'] = [
                    {
                        'filename': f.filename,
                        'mimetype': f.mimetype,
                        'size': len(f.read())
                    }
                    for f in request.files.getlist('files')
                ]

        print(f"[DEBUG] Received /agent/marketing-kit request: {json.dumps(data, indent=2)}")
        kit = build_marketing_kit(data)
        print(f"[DEBUG] Responding with kit: {json.dumps(kit, indent=2)[:1000]}... (truncated)")
        return jsonify(kit)
    except Exception as e:
        print(f"[ERROR] Exception in /agent/marketing-kit: {e}")
        return jsonify({'error': str(e)}), 500

if __name__ == '__main__':
    app.run(port=7000, debug=True)
